account/urls.py
from django.urls import path

from account.views.api_views import UserAPIView
from account.views.user import register, user_login, user_logout, activate
from account.views.password import *

app_name = 'account'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', register, name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
]

urlpatterns += [
    path('password-change/', CustomPasswordChangeView.as_view(), name='password-change'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password-reset'),
    path('password-change/done/', CustomPasswordChangeDoneView.as_view(), name='password-change-done'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('password-reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('test/', UserAPIView.as_view(), name='test'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Мой Блог{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'account:login' %}">Войти</a></li>
        </ul>
    </nav>
</header>

<main>
    {% block content %}
    {% endblock %}
</main>

<footer>
    <p>© 2023 Мой Блог. Все права защищены.</p>
</footer>
</body>
</html>